#!/bin/bash

input="/home/bemoss/testing/test_scripts/PIIP.txt"
while IFS=read line
do
	

sshpass -p "BradleyEE" ssh -o StrictHostKeyChecking=no pi@echo "$line" "python /home/pi/testing_scripts/XBEETEST.py" 

done <"$file"
